<?php
// Copy to config/config.php and set a password hash generated by:
// php -r "echo password_hash('change-me', PASSWORD_DEFAULT), PHP_EOL;"
return [
    'app_name' => 'AgentHub',
    'version' => '1.0.0-php',
    'timezone' => 'Asia/Taipei',
    'base_path' => '', // Empty derives / or /agenthub from the current URL.
    'admin_username' => 'admin',
    'admin_sender' => '管理者',
    'admin_password_hash' => '',
    'db' => [
        'dsn' => 'mysql:host=127.0.0.1;port=3306;dbname=agenthub;charset=utf8mb4',
        'username' => 'agenthub',
        'password' => 'change-me',
    ],
    'storage_dir' => __DIR__ . '/../storage',
    'max_file_bytes' => 104857600,
    'max_message_bytes' => 1048576,
    'agent_lease_seconds' => 15,
];
